### ISSUE TITLE
Make Test and Fake configuration runable without any specific libraries installed

### ISSUE THREAD

**Issue by ThomasHauth** [roced-scheduler/ROCED#1]
At the moment, the novaclient library must be installed, even if the OpenStack adapter is not used at all.

**Comment by ThomasHauth** [comment]
maybe like this:
http://stackoverflow.com/questions/951124/dynamic-loading-of-python-modules

**Comment by Fra-nk** [comment]
Added new branch #7 which should resolve this issue.
